name: Cypress

on: [push, pull_request]

jobs:
  test:
    name: Run Cypress tests
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 12.x

    - name: Setup cache (carton)
      uses: actions/cache@v3
      with:
        path: local
        key: ubuntu-22-carton-${{ hashFiles('cpanfile.snapshot') }}

    - name: Setup cache (cypress)
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ubuntu-22-node-12-cypress-3.8.3-coverage

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y gettext
        npm install cypress@3.8.3 @cypress/code-coverage@3.9.4
        vendor/bin/carton install --deployment
        commonlib/bin/gettext-makemo FixMyStreet
        echo "$(npm bin)" >> $GITHUB_PATH

    - name: Run Cypress tests
      run: |
        bin/browser-tests --coverage run ${CYPRESS_RECORD_KEY:+--record}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    - name: Upload code coverage results
      if: success()
      continue-on-error: true
      uses: Wandalen/wretry.action@master
      with:
        action: codecov/codecov-action@v3
        with: |
          files: ./coverage/lcov.info
          fail_ci_if_error: true
        attempt_limit: 5
        attempt_delay: 10000
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#    - name: Archive code coverage results
#      uses: actions/upload-artifact@v2
#      with:
#        name: code-coverage-report
#        path: coverage/lcov-report
